#!/usr/bin/python

import sys
import os
import common

if len(sys.argv) != 2:
    print "usage: %s [players-file]" % sys.argv[0]
    print "     : [players-file] generated by mercadoparser.py using mercado's HTML pages"
    print "Prints to stdout a list of colon-separated \":\" rows which contain player-id:[b|a|p]:ACB-pos:height:name"
    print "Bear in mind it conects to the internet to retrieve ACB's position"
    raise SystemExit

if not os.path.isfile(sys.argv[1]):
    print sys.argv[1] + " is not a file"
    raise SystemExit

playersFile = open(sys.argv[1], 'r')
for line in playersFile:
    line = line.rstrip() # remove \n at the end of line

    prevLineFound = False
    elems = line.split(':')
    (acbPos, height) = common.GetPlayersPosAndHeightFromInternet(elems[0])
    if acbPos == "" or height == "":
        print "Could not retrieve ACB info for player %s (%s)" % (elems[0], elems[2])
        raise SystemExit
        
    print ("%s:%s:%s:%s:%s") % (elems[0], elems[1].lower(), acbPos.lower(), height, elems[2])

playersFile.close()

